/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDashboardQuotesRouteImport } from './routes/_authenticated/dashboard/quotes'
import { Route as AuthenticatedConfiguratorStandardRouteImport } from './routes/_authenticated/configurator/standard'
import { Route as AuthenticatedCatalogKitsRouteImport } from './routes/_authenticated/catalog/kits'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardQuotesRoute =
  AuthenticatedDashboardQuotesRouteImport.update({
    id: '/dashboard/quotes',
    path: '/dashboard/quotes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguratorStandardRoute =
  AuthenticatedConfiguratorStandardRouteImport.update({
    id: '/configurator/standard',
    path: '/configurator/standard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCatalogKitsRoute =
  AuthenticatedCatalogKitsRouteImport.update({
    id: '/catalog/kits',
    path: '/catalog/kits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/catalog/kits': typeof AuthenticatedCatalogKitsRoute
  '/configurator/standard': typeof AuthenticatedConfiguratorStandardRoute
  '/dashboard/quotes': typeof AuthenticatedDashboardQuotesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/catalog/kits': typeof AuthenticatedCatalogKitsRoute
  '/configurator/standard': typeof AuthenticatedConfiguratorStandardRoute
  '/dashboard/quotes': typeof AuthenticatedDashboardQuotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/catalog/kits': typeof AuthenticatedCatalogKitsRoute
  '/_authenticated/configurator/standard': typeof AuthenticatedConfiguratorStandardRoute
  '/_authenticated/dashboard/quotes': typeof AuthenticatedDashboardQuotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/catalog/kits'
    | '/configurator/standard'
    | '/dashboard/quotes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/catalog/kits'
    | '/configurator/standard'
    | '/dashboard/quotes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/catalog/kits'
    | '/_authenticated/configurator/standard'
    | '/_authenticated/dashboard/quotes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/quotes': {
      id: '/_authenticated/dashboard/quotes'
      path: '/dashboard/quotes'
      fullPath: '/dashboard/quotes'
      preLoaderRoute: typeof AuthenticatedDashboardQuotesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configurator/standard': {
      id: '/_authenticated/configurator/standard'
      path: '/configurator/standard'
      fullPath: '/configurator/standard'
      preLoaderRoute: typeof AuthenticatedConfiguratorStandardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/catalog/kits': {
      id: '/_authenticated/catalog/kits'
      path: '/catalog/kits'
      fullPath: '/catalog/kits'
      preLoaderRoute: typeof AuthenticatedCatalogKitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCatalogKitsRoute: typeof AuthenticatedCatalogKitsRoute
  AuthenticatedConfiguratorStandardRoute: typeof AuthenticatedConfiguratorStandardRoute
  AuthenticatedDashboardQuotesRoute: typeof AuthenticatedDashboardQuotesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCatalogKitsRoute: AuthenticatedCatalogKitsRoute,
  AuthenticatedConfiguratorStandardRoute:
    AuthenticatedConfiguratorStandardRoute,
  AuthenticatedDashboardQuotesRoute: AuthenticatedDashboardQuotesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
